services:
  catalogdb:
    container_name: catalogdb
    environment:
      - MSSQL_SA_PASSWORD=Admin123.      
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - db_catalog:/var/opt/mssql 
 